CC=g++
LD=g++
MM=g++

# DEBUG = 0
# PROFILE = 0

BINDIR = ./bin
BUILDDIR = ./build
SRCDIR = ./src
COMMONDIR = $(SRCDIR)/common
TESTDIR = $(SRCDIR)/test
MEXDIR = $(SRCDIR)/mex
CMDDIR = $(SRCDIR)/cmd

CXXFLAGS=-I$(SRCDIR)/common --std=c++11 -pedantic -Wall
ifdef DEBUG
CXXFLAGS:=$(CXXFLAGS) -g -O0 -DMAS_DEBUG
else
CXXFLAGS:=$(CXXFLAGS) -O3
endif

MMFLAGS:=$(CXXFLAGS) -MM
LDFLAGS:= -pthread

ifdef PROFILE
CXXFLAGS:=$(CXXFLAGS) -pg
LDFLAGS:=$(LDFLAGS) -pg
endif

# Library extension
ifndef LIB_EXT
LIB_EXT:=dll
endif

# Matlab
# Matlab folders
ifndef MATLAB_ROOT

# Guess where matlab root is
MATLAB_GUESS:=$(subst C:/Program Files/MATLAB/,,$(wildcard C:/Program\ Files/MATLAB/*))

ifeq (,$(MATLAB_GUESS))
$(error Cannot find MATLAB, re-run make by passing a MATLAB root folder: make -f Makefile.windows MATLAB_ROOT=<pathname>)
endif
MATLAB_ROOT:="C:/Program Files/MATLAB/$(MATLAB_GUESS)"
$(warning guessing Matlab: $(MATLAB_ROOT))

endif

ifndef MATLAB_BINDIR
MATLAB_BINDIR:="$(subst $\",,$(MATLAB_ROOT))/bin/win64"
endif

ifndef MEX_EXT
MEX_EXT:=mexw64
endif

ifndef MATLAB_INCLUDEDIR
MATLAB_INCLUDEDIR := "$(subst $\",,$(MATLAB_ROOT))/extern/include"
endif

MEX_CXXFLAGS:=$(CXXFLAGS) -I$(MEXDIR) -DMX_COMPAT_32 -DMATLAB_MEX_FILE -I$(MATLAB_INCLUDEDIR) -Wall
MEX_LDFLAGS:= $(LDFLAGS) -shared -L$(MATLAB_BINDIR) -lstdc++ -lmex -lmx -lmat
MEX_MMFLAGS:=$(MEX_CXXFLAGS) -MM

# source file definitions
-include MakefileSources.mk

COMMON_DEPS := $(patsubst $(COMMONDIR)/%.cxx, $(BUILDDIR)/%.d, $(COMMON_SOURCES))
COMMON_OBJECTS := $(patsubst $(COMMONDIR)/%.cxx, $(BUILDDIR)/%.o, $(COMMON_SOURCES))

MEX_DEPS = $(patsubst $(MEXDIR)/%.cxx, $(BUILDDIR)/%.mexd, $(MEX_SOURCES))
MEX_OBJECTS = $(patsubst $(MEXDIR)/%.cxx, $(BUILDDIR)/%.mexo, $(MEX_SOURCES))

CMD_DEPS =  $(patsubst $(CMDDIR)/%.cxx, $(BUILDDIR)/%.cmdd, $(CMD_SOURCES))
CMD_OBJECTS =  $(patsubst $(CMDDIR)/%.cxx, $(BUILDDIR)/%.cmdo, $(CMD_SOURCES))

TEST_DEPS := $(patsubst $(TESTDIR)/%.cxx, $(BUILDDIR)/%.td, $(TEST_SOURCES))
TEST_OBJECTS := $(patsubst $(TESTDIR)/%.cxx, $(BUILDDIR)/%.to, $(TEST_SOURCES))

# Generated outputs, remove _mex and _cmd from filenames
MEX = $(patsubst $(MEXDIR)/%_mex.cxx, $(BINDIR)/%.$(MEX_EXT), $(MEX_SOURCES))
CMD =  $(patsubst $(CMDDIR)/%_cmd.cxx, $(BINDIR)/%, $(CMD_SOURCES))
TEST_CMD := $(patsubst $(TESTDIR)/%.cxx, $(BINDIR)/%, $(TEST_SOURCES))
M_FILES := $(patsubst $(MEXDIR)/%.m, $(BINDIR)/%.m, $(M_SOURCES))

# Common library
COMMON_LIB := $(BINDIR)/libmaslib.$(LIB_EXT)

# Commands
MKDIR_CMD=if not exist "$(@D)" mkdir "$(@D)"
RM_CMD=del /F /Q

default: mex

WIN_TEMP := $(COMMON_OBJECTS) $(COMMON_DEPS) $(MEX_OBJECTS) $(MEX_DEPS) $(CMD_OBJECTS) $(CMD_DEPS) $(TEST_OBJECTS) $(TEST_DEPS)
WIN_TEMP := $(subst /,\,$(WIN_TEMP))

WIN_OUT := $(MEX) $(CMD) $(TEST_CMD) $(M_FILES) $(COMMON_LIB)
WIN_OUT := $(subst /,\,$(WIN_OUT))

cleanup:
	@FOR %%G IN ($(WIN_TEMP)) DO if exist %%G $(RM_CMD) %%G

clean: cleanup
	@FOR %%G IN ($(WIN_OUT)) DO if exist %%G $(RM_CMD) %%G

# do not delete intermediates
.SECONDARY:

vars:
	@echo MATLAB_ROOT: $(MATLAB_ROOT)
	@echo MATLAB_INCLUDEDIR: $(MATLAB_INCLUDEDIR)
	@echo MATLAB_BINDIR: $(MATLAB_BINDIR)
	@echo CXXFLAGS: $(CXXFLAGS)
	@echo COMMON_SOURCES: $(COMMON_SOURCES)
	@echo COMMON_OBJECTS: $(COMMON_OBJECTS)
	@echo MEX_OBJECTS: $(MEX_OBJECTS)
	@echo MEX_CXXFLAGS: $(MEX_CXXFLAGS)
	@echo MEX_LDFLAGS: $(MEX_LDFLAGS)
	@echo MEX: $(MEX)
	@echo M_FILES: $(M_FILES)
	@echo CMD: $(CMD)
	@echo CMD_SOURCES: $(CMD_SOURCES)
	@echo CMD_OBJECTS: $(CMD_OBJECTS)
	@echo CMD: $(CMD)
	@echo TEST_OBJECTS: $(TEST_OBJECTS)
	@echo TEST_CMD: $(TEST_CMD)	

all: cmd lib mex test

doc:
	@doxygen doc/maslib.doxyfile

mex: $(MEX) $(M_FILES)

cmd: $(CMD)

lib: $(COMMON_LIB)

test: $(TEST_CMD)

deps: $(COMMON_DEPS) $(MEX_DEPS) $(CMD_DEPS) $(TEST_DEPS)

# include dependency rules	
-include $(COMMON_DEPS)
-include $(MEX_DEPS)
-include $(CMD_DEPS)
-include $(TEST_DEPS)
	
# DEPENDENCIES
$(BUILDDIR)/%.d: $(COMMONDIR)/%.cxx
	@$(MKDIR_CMD)
	@echo Updating dependencies $@...
	@$(MM) $(MMFLAGS) -MT $(@:.d=.o) $< >> $@

$(BUILDDIR)/%.mexd: $(MEXDIR)/%.cxx
	@$(MKDIR_CMD)
	@echo Updating dependencies $@...
	@$(MM) $(MEX_MMFLAGS) -MT $(@:.mexd=.mexo) $< >> $@

$(BUILDDIR)/%.cmdd: $(CMDDIR)/%.cxx
	@$(MKDIR_CMD)
	@echo Updating dependencies $@...
	@$(MM) $(MMFLAGS) -MT $(@:.cmdd=.cmdo) $< >> $@
	
$(BUILDDIR)/%.td: $(TESTDIR)/%.cxx
	@$(MKDIR_CMD)
	@echo Updating dependencies $@...
	@$(MM) $(MMFLAGS) -MT $(@:.td=.to) $< >> $@

# OBJECTS

$(BUILDDIR)/%.o: $(COMMONDIR)/%.cxx
	@echo Compiling $@...
	@$(CC) $(CXXFLAGS) -o $@ -c $<

$(BUILDDIR)/%.mexo: $(MEXDIR)/%.cxx
	@echo Compiling $@...
	@$(CC) $(MEX_CXXFLAGS) -o $@ -c $<

$(BUILDDIR)/%.cmdo: $(CMDDIR)/%.cxx
	@echo Compiling $@...
	@$(CC) $(CXXFLAGS) -o $@ -c $<
	
$(BUILDDIR)/%.to: $(TESTDIR)/%.cxx
	@echo Compiling $@...
	@$(CC) $(CXXFLAGS) -o $@ -c $<

# Matlab
$(BINDIR)/%.$(MEX_EXT): $(BUILDDIR)/%_mex.mexo $(COMMON_OBJECTS)
	@$(MKDIR_CMD)
	@echo Assembling $@ ...
	@$(LD) -o $@ $(MEX_LDFLAGS) $(COMMON_OBJECTS) $<
	
$(BINDIR)/%.m: $(MEXDIR)/%.m
	@$(MKDIR_CMD)
	@echo Copying $@ ...
	@copy "$(subst /,\,$<)" "$(subst /,\,$@)" > nul

# Command-line programs
		
$(BINDIR)/%: $(BUILDDIR)/%_cmd.cmdo $(COMMON_OBJECTS)
	@$(MKDIR_CMD)
	@echo Assembling $@ ...
	@$(LD) -o $@ $(LDFLAGS) $(COMMON_OBJECTS) $<
	
$(BINDIR)/%: $(BUILDDIR)/%.to $(COMMON_OBJECTS)
	@$(MKDIR_CMD)
	@echo Assembling $@ ...
	@$(LD) -o $@ $(LDFLAGS) $(COMMON_OBJECTS) $<
	
$(COMMON_LIB) : $(COMMON_OBJECTS)
	@$(MKDIR_CMD)
	@echo Assembling $@ ...
	@$(LD) -o $@ $(LDFLAGS) -fPIC -shared $(COMMON_OBJECTS)
